### ISSUE TITLE
请求

### ISSUE THREAD

**Issue by chenquan2002** [ai4ce/SeeDo#2]
作者您好！上传的文件中貌似少了simulation.py。请问能上传一下吗？

**Comment by YushunXiang** [comment]
me too

**Comment by xsw1208** [comment]
The requirement.txt for configuration is also missed.

**Comment by aakash2002** [comment]
Having the same issue with missing requirements.txt. Appreciate if we could get an update on this :)

**Comment by BWangCN** [comment]
> Having the same issue with missing requirements.txt. Appreciate if we could get an update on this :)



> The requirement.txt for configuration is also missed.

Hello, the requirements.txt has been uploaded.

**Comment by BWangCN** [comment]
> 作者您好！上传的文件中貌似少了simulation.py。请问能上传一下吗？



> me too

Hello, we are still working on cleaning code for simulation.py. We will release them soon and will let you know as soon as possible.

**Comment by BWangCN** [comment]
> 作者您好！上传的文件中貌似少了simulation.py。请问能上传一下吗？



> me too

Hello, the simulation.py has been uploaded. Please make sure you also download the modelings provided on hugging face. The details are implemented in README.
