### ISSUE TITLE
ImportError: cannot import name 'load_image_from_array' from 'groundingdino.util.inference'

### ISSUE THREAD

**Issue by YushunXiang** [ai4ce/SeeDo#3]
I found that [inference.py](https://github.com/IDEA-Research/GroundingDINO/blob/main/groundingdino/util/inference.py) did not have `load_image_from array` function.

**Comment by TinnkE** [comment]
I also encountered this problem. Is there any solution to this problem now？

**Comment by BWangCN** [comment]
> I found that [inference.py](https://github.com/IDEA-Research/GroundingDINO/blob/main/groundingdino/util/inference.py) did not have `load_image_from array` function.



> I also encountered this problem. Is there any solution to this problem now？

Hello, please refer to the updated README, we have resolved this problem
